application: wina-assignment
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# These are checked in order, so it tries to match static first then falls back to Django
handlers:
- url: /static
  static_dir: static
# Reference to the application variable in wina/wsgi.py
- url: .*
  script: wina.wsgi.application
  # Force https for added security, particuarly important for the API
  secure: always

libraries:
- name: django
  version: '1.5'
- name: MySQLdb
  version: "latest"